<?php

namespace App\Console\Commands;

use App\Models\AutoscaleRun;
use App\Services\AuditService;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;

/**
 * autoscale:revert — rewind the active run to the mapping start point
 * (re-engineering 2026-07-19; the operator's iteration protocol as one
 * command: run → check → halt → fix → REVERT → resume, until clean).
 *
 * Deletes ONLY autoscale-generated mapping output, identified by the maps'
 * provenance descriptions ('Auto-generated by full-scale autoscale …').
 * Adopted operator maps are never tagged → never touched. Keeps: sizing
 * (all legislatures), the bootstrap board, the audit chain (append-only —
 * a revert APPENDS an event, never deletes history), and every global
 * precompute table (geometry-derived: paid once per geometry, not per
 * attempt).
 *
 *   --keep-singles  keep the ~900k leaf-council maps; reset sweeps only
 *                   (the default iteration when a fix touches sweep scoring)
 *   --resume        clear the halt flag so the pump takes over immediately
 *   --force         skip the halted/done guard (live leases may be working!)
 */
class AutoscaleRevertCommand extends Command
{
    protected $signature = 'autoscale:revert {--keep-singles} {--resume} {--force}';

    protected $description = 'Rewind the autoscale run to the mapping start: delete generated maps, reset items, keep sizing + precompute';

    public function handle(): int
    {
        $run = AutoscaleRun::query()
            ->whereIn('status', ['queued', 'sizing', 'mapping', 'halted', 'done'])
            ->orderByDesc('created_at')
            ->first();
        if ($run === null) {
            $this->error('No autoscale run found.');

            return self::FAILURE;
        }

        if (! in_array($run->status, ['halted', 'done'], true) && ! $this->option('force')) {
            $this->error("Run {$run->id} is {$run->status} — halt it first (or --force).");

            return self::FAILURE;
        }

        $liveLeases = (int) DB::table('autoscale_worker_leases')
            ->where('run_id', $run->id)
            ->where('last_seen_at', '>', now()->subMinutes(2))
            ->count();
        if ($liveLeases > 0 && ! $this->option('force')) {
            $this->error("{$liveLeases} worker lease(s) still live — wait for workers to park (≤2 min) or --force.");

            return self::FAILURE;
        }

        $keepSingles = (bool) $this->option('keep-singles');

        // Cycle-2 leaf law: an over-ceiling leaf's at-large map is WRONG
        // (a truncated 9-seat council for a line-split-sized legislature) —
        // keeping singles would strand them behind the adopt guard.
        if ($keepSingles) {
            $ceiling = \App\Services\ConstitutionalDefaults::ceiling();
            $overCeilingSingles = (int) DB::table('autoscale_items as ai')
                ->join('legislatures as l', 'l.id', '=', 'ai.legislature_id')
                ->where('ai.run_id', $run->id)
                ->where('ai.kind', 'single')
                ->where('l.type_a_seats', '>', $ceiling)
                ->count();
            if ($overCeilingSingles > 0) {
                $this->error("--keep-singles refused: {$overCeilingSingles} single items are over-ceiling under the leaf law and must re-enumerate as line-split sweeps. Run a full revert.");

                return self::FAILURE;
            }
        }

        // Provenance selectors — the two autoscale map descriptions are
        // distinct on purpose ('single at-large district' vs 'mixed autoseed
        // sweep'); operator/adopted maps carry neither.
        $sweepLike   = 'Auto-generated by full-scale autoscale%mixed autoseed sweep%';
        $singlesLike = 'Auto-generated by full-scale autoscale%single at-large district%';

        $this->info('Deleting autoscale-generated mapping output'
            . ($keepSingles ? ' (sweep maps only — singles kept)' : ' (sweep + singles maps)') . ' …');

        $likes = $keepSingles ? [$sweepLike] : [$sweepLike, $singlesLike];
        foreach ($likes as $like) {
            DB::statement('
                DELETE FROM district_subdivisions ds
                 USING legislature_district_maps m
                 WHERE ds.map_id = m.id AND m.description LIKE ?
            ', [$like]);
            DB::statement('
                DELETE FROM legislature_district_jurisdictions ldj
                 USING legislature_districts d, legislature_district_maps m
                 WHERE ldj.district_id = d.id AND d.map_id = m.id AND m.description LIKE ?
            ', [$like]);
            DB::statement('
                DELETE FROM legislature_districts d
                 USING legislature_district_maps m
                 WHERE d.map_id = m.id AND m.description LIKE ?
            ', [$like]);
            DB::statement('
                DELETE FROM legislature_district_maps m
                 WHERE m.description LIKE ?
            ', [$like]);
        }

        $this->info('Resetting run state …');

        // Post-delete hygiene (2026-07-19, the 72-minute-mint lesson):
        // deleting ~a million map rows leaves bloated pages + stale stats,
        // and any mass UPDATE of legislatures (the resize repair) leaves
        // dead row versions that make every FK probe from the mint ~1 ms
        // (measured: the RI trigger at 2 s per 2,000 rows). VACUUM ANALYZE
        // collapses both before the set-based tail; parallelism stays off
        // for the planet-wide passes (the /dev/shm lesson).
        DB::statement('SET max_parallel_workers_per_gather = 0');
        foreach (['legislature_district_maps', 'legislature_districts',
                  'district_subdivisions', 'legislature_district_jurisdictions',
                  'legislatures'] as $t) {
            DB::statement("VACUUM ANALYZE {$t}");
        }

        // Scopes are derived state — a fresh mapping phase re-mints roots.
        DB::table('autoscale_scopes')->where('run_id', $run->id)->delete();

        // Sweep items → pending. map_id cleared (the map was just deleted);
        // the re-mint below issues fresh draft founding maps.
        DB::table('autoscale_items')
            ->where('run_id', $run->id)
            ->where('kind', 'sweep')
            ->update([
                'status'       => 'pending',
                'claim_token'  => null,
                'map_id'       => null,
                'seats_seated' => null,
                'drift'        => null,
                'reason'       => null,
                'started_at'   => null,
                'finished_at'  => null,
                'updated_at'   => now(),
            ]);

        if (! $keepSingles) {
            DB::table('autoscale_items')
                ->where('run_id', $run->id)
                ->where('kind', 'single')
                ->update([
                    'status'       => 'pending',
                    'claim_token'  => null,
                    'seats_seated' => null,
                    'drift'        => null,
                    'reason'       => null,
                    'started_at'   => null,
                    'finished_at'  => null,
                    'updated_at'   => now(),
                ]);
        }

        // Re-derive the ordering foundation: child_count from live children.
        DB::statement('
            UPDATE autoscale_items ai
               SET child_count = cc.n
              FROM (
                    SELECT ai2.id, COUNT(c.id)::int AS n
                      FROM autoscale_items ai2
                      LEFT JOIN jurisdictions c
                             ON c.parent_id = ai2.jurisdiction_id AND c.deleted_at IS NULL
                     WHERE ai2.run_id = ?
                     GROUP BY ai2.id
              ) cc
             WHERE ai.id = cc.id
        ', [$run->id]);

        // Cycle-2 kind flip (leaf law): sweep = has children OR over-ceiling
        // (a leaf legislature line-splitting itself); single = in-band
        // childless leaf. seats_expected refreshes from the (possibly
        // resize-repaired) lawful size. Runs BEFORE the enumeration tail so
        // the founding-map mint + root scopes cover flipped items.
        $ceiling = \App\Services\ConstitutionalDefaults::ceiling();
        DB::statement("
            UPDATE autoscale_items ai
               SET kind = CASE WHEN ai.child_count > 0 OR l.type_a_seats > ? THEN 'sweep' ELSE 'single' END,
                   seats_expected = l.type_a_seats,
                   updated_at = now()
              FROM legislatures l
             WHERE l.id = ai.legislature_id
               AND ai.run_id = ?
               AND ai.status = 'pending'
        ", [$ceiling, $run->id]);

        // Fresh stats + dead-version cleanup for the items table too
        // (statuses/kinds just flipped en masse) before the keys + the
        // enumeration tail's anti-joins.
        DB::statement('VACUUM ANALYZE autoscale_items');

        // The operator's simplest-first ordering (est_districts, cascade
        // height, position) — shared with the sizing job so re-derivation
        // can never drift from enumeration.
        \App\Support\AutoscaleEnumeration::deriveOrderingKeys((string) $run->id, $ceiling);

        // Re-run the enumeration tail set-based: adopt pre-pass, founding-map
        // mint + stamp, root scopes (same statements as AutoscaleSizingJob B2–B4).
        DB::statement("
            UPDATE autoscale_items ai
               SET status = 'done',
                   reason = 'adopted: an active map with districts already exists',
                   seats_seated = s.seated,
                   drift = s.seated - COALESCE(ai.seats_expected, 0),
                   started_at = COALESCE(ai.started_at, now()),
                   finished_at = now(),
                   updated_at = now()
              FROM (
                    SELECT ai2.id, SUM(d.seats) AS seated
                      FROM autoscale_items ai2
                      JOIN legislature_district_maps m
                             ON m.legislature_id = ai2.legislature_id
                            AND m.status = 'active' AND m.deleted_at IS NULL
                      JOIN legislature_districts d
                             ON d.map_id = m.id AND d.deleted_at IS NULL
                     WHERE ai2.run_id = ? AND ai2.kind = 'sweep' AND ai2.status = 'pending'
                     GROUP BY ai2.id
              ) s
             WHERE ai.id = s.id
               AND ai.status = 'pending'
        ", [$run->id]);
        DB::statement("
            INSERT INTO legislature_district_maps
                (id, legislature_id, name, description, status, created_at, updated_at)
            SELECT gen_random_uuid(), ai.legislature_id, 'Founding Map',
                   'Auto-generated by full-scale autoscale (True All Scale, 2026-07-18) — mixed autoseed sweep.',
                   'draft', now(), now()
              FROM autoscale_items ai
             WHERE ai.run_id = ? AND ai.kind = 'sweep' AND ai.status = 'pending'
               AND NOT EXISTS (SELECT 1 FROM legislature_district_maps m
                                WHERE m.legislature_id = ai.legislature_id
                                  AND m.name = 'Founding Map'
                                  AND m.deleted_at IS NULL)
        ", [$run->id]);
        DB::statement("
            UPDATE autoscale_items ai
               SET map_id = fm.id, updated_at = now()
              FROM (
                    SELECT DISTINCT ON (legislature_id) id, legislature_id
                      FROM legislature_district_maps
                     WHERE name = 'Founding Map' AND deleted_at IS NULL
                     ORDER BY legislature_id, created_at DESC
              ) fm
             WHERE ai.run_id = ? AND ai.kind = 'sweep' AND ai.map_id IS NULL
               AND fm.legislature_id = ai.legislature_id
        ", [$run->id]);
        DB::statement("
            INSERT INTO autoscale_scopes
                (id, run_id, item_id, legislature_id, scope_jurisdiction_id,
                 depth, status, created_at, updated_at)
            SELECT gen_random_uuid(), ?, ai.id, ai.legislature_id, ai.jurisdiction_id,
                   0, 'pending', now(), now()
              FROM autoscale_items ai
             WHERE ai.run_id = ? AND ai.kind = 'sweep' AND ai.status = 'pending'
                ON CONFLICT ON CONSTRAINT autoscale_scopes_scope_uq DO NOTHING
        ", [$run->id, $run->id]);

        // Fresh counters (kind flips change the TOTALS too); run parks
        // halted unless --resume.
        $counts = DB::table('autoscale_items')
            ->where('run_id', $run->id)
            ->selectRaw("
                COUNT(*) FILTER (WHERE kind = 'single')                     AS singles_total,
                COUNT(*) FILTER (WHERE kind = 'sweep')                      AS sweeps_total,
                COUNT(*) FILTER (WHERE kind = 'single' AND status = 'done') AS singles_done,
                COUNT(*) FILTER (WHERE kind = 'sweep'  AND status = 'done') AS sweeps_done,
                COUNT(*) FILTER (WHERE status = 'review')                   AS review_count
            ")->first();

        $resume = (bool) $this->option('resume');
        $run->forceFill([
            'status'            => $resume ? 'mapping' : 'halted',
            'halt_requested_at' => $resume ? null : ($run->halt_requested_at ?? now()),
            'finished_at'       => null,
            'singles_total'     => (int) $counts->singles_total,
            'sweeps_total'      => (int) $counts->sweeps_total,
            'singles_done'      => (int) $counts->singles_done,
            'sweeps_done'       => (int) $counts->sweeps_done,
            'review_count'      => (int) $counts->review_count,
            'updated_at'        => now(),
        ])->save();

        app(AuditService::class)->append(
            module: 'elections',
            event: 'autoscale.reverted',
            payload: [
                'run_id'       => (string) $run->id,
                'keep_singles' => $keepSingles,
                'resumed'      => $resume,
                'generator'    => 'AutoscaleRevertCommand (pull engine, 2026-07-19)',
            ],
            ref: 'WF-ELE-02',
        );

        $this->info(sprintf(
            'Reverted run %s to the mapping start (singles %s). Status: %s.%s',
            $run->id,
            $keepSingles ? 'kept' : 'reset',
            $run->status,
            $resume ? ' The pump takes over within a minute.' : ' Resume from the dashboard (or --resume) when ready.',
        ));

        return self::SUCCESS;
    }
}
