<?php

namespace App\Console\Commands;

use App\Models\AutoscaleRun;
use App\Services\AuditService;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;

/**
 * autoscale:revert — THE BENCHMARK RESET (single-home law, 2026-08-31):
 * facts untouched, work state cleared, drawn output deleted.
 *
 * Facts (the world build's product) survive every reset: the ledger
 * headers and scope trees, ordering + block keys, gate verdicts, the
 * founding-map CONTAINERS (auto-generated maps flip active→draft instead
 * of deleting), all legislatures, the bootstrap board, the audit chain
 * (append-only — a reset APPENDS an event), and every geometry precompute.
 *
 * Work state resets in bounded chunks (the ETL rule): header map_status →
 * pending (gate-refused headers → review, their standing verdict), scope
 * status → pending, claims/reasons/timings/retries cleared. Drawn output
 * (districts, memberships, subdivisions) deletes; an adopt pre-pass then
 * re-marks operator-accepted maps done so second-accept counters stay
 * honest.
 *
 *   --keep-singles  keep completed single-district maps; reset sweeps only
 *   --resume        flip straight to mapping with a fresh benchmark clock
 *   --force         skip the halted/done guard (live leases may be working!)
 */
class AutoscaleRevertCommand extends Command
{
    protected $signature = 'autoscale:revert {--keep-singles} {--resume} {--force}';

    protected $description = 'Benchmark reset: delete drawn output, clear ledger work state, keep every fact';

    private const CHUNK = 25000;

    public function handle(): int
    {
        $run = AutoscaleRun::query()
            ->whereIn('status', ['queued', 'sizing', 'mapping', 'halted', 'done'])
            ->orderByDesc('created_at')
            ->first();
        if ($run === null) {
            $this->error('No autoscale run found.');

            return self::FAILURE;
        }

        if (! in_array($run->status, ['halted', 'done'], true) && ! $this->option('force')) {
            $this->error("Run {$run->id} is {$run->status} — halt it first (or --force).");

            return self::FAILURE;
        }

        $liveLeases = (int) DB::table('autoscale_worker_leases')
            ->where('run_id', $run->id)
            ->where('last_seen_at', '>', now()->subMinutes(2))
            ->count();
        if ($liveLeases > 0 && ! $this->option('force')) {
            $this->error("{$liveLeases} worker lease(s) still live — wait for workers to park (≤2 min) or --force.");

            return self::FAILURE;
        }

        $keepSingles = (bool) $this->option('keep-singles');

        // Provenance selectors: only machine-drawn output is ever deleted.
        $sweepLike   = 'Auto-generated by full-scale autoscale%mixed autoseed sweep%';
        $singlesLike = 'Auto-generated by full-scale autoscale%single at-large district%';
        $anyAutoLike = 'Auto-generated by full-scale autoscale%';

        $this->info('Deleting machine-drawn output'
            . ($keepSingles ? ' (sweep maps only — completed singles kept)' : ' (sweep + singles)') . ' …');

        // FAST PATH: at founding-run stage nothing but machine output exists
        // and nothing references it — TRUNCATE the DRAWN tables (never the
        // map containers: they are world-build facts now).
        $truncated = false;
        if (! $keepSingles && DB::transactionLevel() === 0) {
            $nonAutoscale = (int) DB::table('legislature_district_maps')
                ->where('description', 'not like', $anyAutoLike)
                ->count();
            $refRows = (int) DB::table('elections')->count()
                + (int) DB::table('election_races')->count()
                + (int) DB::table('legislature_members')->count();
            if ($nonAutoscale === 0 && $refRows === 0) {
                try {
                    DB::statement('
                        TRUNCATE legislature_districts,
                                 legislature_district_jurisdictions, district_subdivisions,
                                 elections, election_races, legislature_members
                    ');
                    $truncated = true;
                    $this->info('  TRUNCATE fast path (no operator maps, no seated world yet) — containers kept.');
                } catch (\Throwable $e) {
                    $this->warn('  TRUNCATE fast path unavailable ('.$e->getMessage().') — falling back to surgical deletes.');
                }
            }
        }

        if (! $truncated) {
            $likes = $keepSingles ? [$sweepLike] : [$sweepLike, $singlesLike];
            foreach ($likes as $like) {
                $n = DB::delete('
                    DELETE FROM district_subdivisions ds
                     USING legislature_district_maps m
                     WHERE ds.map_id = m.id AND m.description LIKE ?
                ', [$like]);
                $this->info("  district_subdivisions deleted: {$n}");
                $n = DB::delete('
                    DELETE FROM legislature_district_jurisdictions ldj
                     USING legislature_districts d, legislature_district_maps m
                     WHERE ldj.district_id = d.id AND d.map_id = m.id AND m.description LIKE ?
                ', [$like]);
                $this->info("  memberships deleted: {$n}");
                $n = DB::delete('
                    DELETE FROM legislature_districts d
                     USING legislature_district_maps m
                     WHERE d.map_id = m.id AND m.description LIKE ?
                ', [$like]);
                $this->info("  districts deleted: {$n}");
            }
        }

        // Containers are FACTS: machine maps return to draft, never deleted.
        // (Chunked — the ETL rule binds resets too.)
        $this->info('Returning machine containers to draft (chunked) …');
        $likes = $keepSingles ? [$sweepLike] : [$anyAutoLike];
        foreach ($likes as $like) {
            do {
                $n = DB::update("
                    UPDATE legislature_district_maps m
                       SET status = 'draft', effective_start = NULL, effective_end = NULL, updated_at = now()
                     WHERE m.id IN (
                           SELECT id FROM legislature_district_maps
                            WHERE description LIKE ? AND status <> 'draft' AND deleted_at IS NULL
                            LIMIT " . self::CHUNK . '
                     )
                ', [$like]);
            } while ($n > 0);
        }

        $this->info('Clearing ledger work state (chunked) …');
        // Headers → pending; gate-refused headers return to REVIEW with
        // their standing verdict (a refusal only moves when data changes).
        $keepPredicate = $keepSingles
            ? "AND NOT (kind = 'single' AND map_status = 'done')"
            : '';
        do {
            $n = DB::update("
                UPDATE apportionment_ledger h
                   SET map_status   = CASE WHEN h.gate_reason IS NOT NULL THEN 'review' ELSE 'pending' END,
                       reason       = h.gate_reason,
                       claim_token  = NULL,
                       seats_seated = NULL,
                       drift        = NULL,
                       started_at   = NULL,
                       finished_at  = NULL,
                       priority_at  = NULL,
                       redraw_requested_at = NULL,
                       transient_retries   = 0,
                       updated_at   = now()
                 WHERE h.legislature_id IN (
                       SELECT legislature_id FROM apportionment_ledger
                        WHERE (map_status NOT IN ('pending', 'review')
                               OR claim_token IS NOT NULL
                               OR seats_seated IS NOT NULL)
                          {$keepPredicate}
                        LIMIT " . self::CHUNK . '
                 )
            ');
        } while ($n > 0);

        do {
            $n = DB::update("
                UPDATE apportionment_ledger_scopes s
                   SET status = 'pending', claim_token = NULL, reason = NULL,
                       started_at = NULL, finished_at = NULL,
                       retry_count = 0, step_timings = NULL, updated_at = now()
                 WHERE s.id IN (
                       SELECT id FROM apportionment_ledger_scopes
                        WHERE status <> 'pending' OR claim_token IS NOT NULL
                        LIMIT " . self::CHUNK . '
                 )
            ');
        } while ($n > 0);

        // Post-delete hygiene: collapse bloat before the adopt pre-pass.
        DB::statement('SET max_parallel_workers_per_gather = 0');
        if (DB::transactionLevel() === 0) {
            foreach (['legislature_district_maps', 'legislature_districts',
                      'district_subdivisions', 'legislature_district_jurisdictions',
                      'apportionment_ledger', 'apportionment_ledger_scopes'] as $t) {
                DB::statement("VACUUM ANALYZE {$t}");
            }
        }

        // Adopt pre-pass (never bulldoze): operator-accepted active maps
        // with districts mark their headers done, netting lawful bonus.
        DB::statement("
            UPDATE apportionment_ledger h
               SET map_status = 'done',
                   reason = 'adopted: an active map with districts already exists',
                   seats_seated = s.seated,
                   drift = (s.seated - s.bonus) - COALESCE(h.head_seats, 0),
                   started_at = COALESCE(h.started_at, now()),
                   finished_at = now(),
                   updated_at = now()
              FROM (
                    SELECT h2.legislature_id,
                           COALESCE(SUM(d.seats), 0)::int AS seated,
                           COALESCE(SUM(d.bonus_seats), 0)::int AS bonus
                      FROM apportionment_ledger h2
                      JOIN legislature_district_maps m
                             ON m.legislature_id = h2.legislature_id
                            AND m.status = 'active' AND m.deleted_at IS NULL
                      JOIN legislature_districts d
                             ON d.map_id = m.id AND d.deleted_at IS NULL
                     WHERE h2.map_status = 'pending'
                     GROUP BY h2.legislature_id
              ) s
             WHERE h.legislature_id = s.legislature_id
               AND h.map_status = 'pending'
               AND NOT EXISTS (SELECT 1 FROM apportionment_ledger_scopes ps
                                WHERE ps.legislature_id = h.legislature_id
                                  AND ps.scope_kind = 'type_b' AND ps.status <> 'done')
        ");
        // An adopted map whose Type B PANEL scope is still open (operator
        // order 2026-09-05) stays RUNNING, not done: the lanes draw the panel
        // map and the finalize rung closes the header with the adopted map's
        // seat facts — the same posture as the in-run adoption.
        DB::statement("
            UPDATE apportionment_ledger h
               SET map_status = 'running',
                   reason = 'adopted: an active map with districts already exists',
                   started_at = now(), finished_at = NULL, finalize_ready = false,
                   updated_at = now()
             WHERE h.map_status = 'pending'
               AND EXISTS (SELECT 1 FROM legislature_district_maps m
                            JOIN legislature_districts d ON d.map_id = m.id AND d.deleted_at IS NULL
                           WHERE m.legislature_id = h.legislature_id
                             AND m.status = 'active' AND m.deleted_at IS NULL)
               AND EXISTS (SELECT 1 FROM apportionment_ledger_scopes ps
                            WHERE ps.legislature_id = h.legislature_id
                              AND ps.scope_kind = 'type_b' AND ps.status <> 'done')
        ");
        DB::update("
            UPDATE apportionment_ledger_scopes s
               SET status = 'done',
                   reason = 'adopted: an active map with districts already exists',
                   finished_at = now(), updated_at = now()
              FROM apportionment_ledger h
             WHERE h.legislature_id = s.legislature_id
               AND h.map_status IN ('done', 'running') AND h.reason LIKE 'adopted:%'
               AND s.status = 'pending'
               AND s.scope_kind = 'type_a'
        ");

        // Fresh counters; the run parks halted unless --resume (which also
        // restarts the benchmark clock).
        $counts = DB::table('apportionment_ledger')
            ->selectRaw("
                COUNT(*) FILTER (WHERE kind = 'single')                         AS singles_total,
                COUNT(*) FILTER (WHERE kind IS DISTINCT FROM 'single')          AS sweeps_total,
                COUNT(*) FILTER (WHERE kind = 'single' AND map_status = 'done') AS singles_done,
                COUNT(*) FILTER (WHERE kind = 'sweep'  AND map_status = 'done') AS sweeps_done,
                COUNT(*) FILTER (WHERE map_status = 'review')                   AS review_count
            ")->first();

        $resume = (bool) $this->option('resume');
        $run->forceFill([
            'status'             => $resume ? 'mapping' : 'halted',
            'halt_requested_at'  => $resume ? null : ($run->halt_requested_at ?? now()),
            'mapping_started_at' => $resume ? now() : $run->mapping_started_at,
            'finished_at'        => null,
            'singles_total'      => (int) $counts->singles_total,
            'sweeps_total'       => (int) $counts->sweeps_total,
            'singles_done'       => (int) $counts->singles_done,
            'sweeps_done'        => (int) $counts->sweeps_done,
            'review_count'       => (int) $counts->review_count,
            'updated_at'         => now(),
        ])->save();

        app(AuditService::class)->append(
            module: 'elections',
            event: 'autoscale.reverted',
            payload: [
                'run_id'       => (string) $run->id,
                'keep_singles' => $keepSingles,
                'resumed'      => $resume,
                'generator'    => 'AutoscaleRevertCommand (benchmark reset, single home, 2026-08-31)',
            ],
            ref: 'WF-ELE-02',
        );

        $this->info(sprintf(
            'Benchmark reset complete for run %s (singles %s). Status: %s.%s',
            $run->id,
            $keepSingles ? 'kept' : 'reset',
            $run->status,
            $resume ? ' Fresh benchmark clock; the pump takes over within a minute.' : ' Resume from the dashboard (or --resume) when ready.',
        ));

        return self::SUCCESS;
    }
}
