<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Str;
use RuntimeException;

/**
 * matrix:setup — generate the matched secret bundle that wires the CGA appservice, MAS (the game-upstream
 * OIDC delegation, K3-C), Synapse, and LiveKit for a REAL deployment (the dev stack ships matching
 * dev-default secrets, like the repo's APP_KEY). One run produces every secret that must AGREE across the
 * config files, writes the game-side vars to .env, renders the gitignored MAS config (config.generated.yaml,
 * which deploy.sh swaps in), and prints the values the operator places in the sibling YAML files.
 *
 * SECURITY: every value here is freshly random; nothing is committed (config.generated.yaml is gitignored,
 * .env is gitignored). The OIDC client secret is the game↔MAS shared secret; the MAS↔Synapse secret stays
 * the matrix.secret ↔ 20-mas.yaml pair; none of these ever federate.
 */
class MatrixSetupCommand extends Command
{
    protected $signature = 'matrix:setup
        {--issuer= : the GAME public base URL (the OIDC issuer); defaults to APP_URL}
        {--mas-issuer= : MAS public base URL; defaults to matrix.mas.issuer}
        {--server-name= : the Matrix server_name; defaults to matrix.server_name}
        {--env-path= : .env path to update (default: base_path/.env)}
        {--mas-config-path= : MAS config output (default: docker/matrix/mas/config.generated.yaml)}
        {--print-only : show the bundle + sibling-file values, write nothing}';

    protected $description = 'Generate the matched appservice/MAS/Synapse/LiveKit secret bundle for a deployment (K3-C)';

    public function handle(): int
    {
        $issuer = rtrim((string) ($this->option('issuer') ?: config('matrix.oidc.issuer')), '/');
        $masIssuer = rtrim((string) ($this->option('mas-issuer') ?: config('matrix.mas.issuer')), '/');
        $serverName = (string) ($this->option('server-name') ?: config('matrix.server_name'));

        $b = $this->generateBundle($issuer, $masIssuer);

        if ($this->option('print-only')) {
            $this->report($b, $issuer, $masIssuer, $serverName, dryRun: true);

            return self::SUCCESS;
        }

        $envPath = (string) ($this->option('env-path') ?: base_path('.env'));
        $masPath = (string) ($this->option('mas-config-path') ?: base_path('docker/matrix/mas/config.generated.yaml'));

        $this->upsertEnv($envPath, [
            'MATRIX_AS_TOKEN' => $b['as_token'],
            'MATRIX_HS_TOKEN' => $b['hs_token'],
            'LIVEKIT_API_KEY' => $b['livekit_key'],
            'LIVEKIT_API_SECRET' => $b['livekit_secret'],
            'OIDC_MAS_CLIENT_ID' => $b['client_id'],
            'OIDC_MAS_CLIENT_SECRET' => $b['oidc_client_secret'],
            'OIDC_MAS_REDIRECT_URIS' => $b['redirect_uri'],
        ]);

        $this->writeFile($masPath, $this->renderMasConfig($b, $issuer, $masIssuer, $serverName));

        $this->report($b, $issuer, $masIssuer, $serverName, dryRun: false);
        $this->info("[OK] wrote {$envPath} (game vars) and {$masPath} (MAS config).");

        return self::SUCCESS;
    }

    /** @return array<string,string> */
    private function generateBundle(string $issuer, string $masIssuer): array
    {
        $ulid = strtoupper((string) Str::ulid());

        return [
            'as_token' => 'cga_as_'.bin2hex(random_bytes(32)),
            'hs_token' => 'cga_hs_'.bin2hex(random_bytes(32)),
            'mas_synapse_secret' => bin2hex(random_bytes(16)),
            'livekit_key' => 'cga_'.bin2hex(random_bytes(6)),
            'livekit_secret' => bin2hex(random_bytes(24)),
            'client_id' => 'mas-upstream',
            'oidc_client_secret' => bin2hex(random_bytes(32)),
            'provider_ulid' => $ulid,
            'redirect_uri' => $masIssuer.'/upstream/callback/'.$ulid,
            'mas_encryption' => bin2hex(random_bytes(32)),
            'mas_rsa_pem' => $this->pem(['private_key_bits' => 2048, 'private_key_type' => OPENSSL_KEYTYPE_RSA]),
            'mas_ec_pem' => $this->pem(['private_key_type' => OPENSSL_KEYTYPE_EC, 'curve_name' => 'prime256v1']),
        ];
    }

    /** @param array<string,string> $b */
    private function renderMasConfig(array $b, string $issuer, string $masIssuer, string $serverName): string
    {
        $rsa = $this->indentPem($b['mas_rsa_pem']);
        $ec = $this->indentPem($b['mas_ec_pem']);
        $db = (string) env('MATRIX_MAS_DB_URI', 'postgresql://fc_user:fc_password@postgres:5432/matrix_auth');

        // A real deployment has ONE public HTTPS issuer reachable both by the browser and by MAS, so
        // discovery_mode: oidc (vs the dev stack's split-horizon `disabled` in config.yaml).
        return <<<YAML
        # GENERATED by `php artisan matrix:setup` — do NOT edit by hand, do NOT commit (gitignored).
        # MAS (Matrix Authentication Service) for a CGA deployment: the GAME is the upstream OIDC provider
        # (K3-C), the homeserver never sees a password, only the pseudonym crosses to Matrix.
        http:
          listeners:
          - name: web
            resources:
            - name: discovery
            - name: human
            - name: oauth
            - name: compat
            - name: graphql
            - name: assets
            binds:
            - address: '[::]:8080'
          - name: internal
            resources:
            - name: health
            binds:
            - host: localhost
              port: 8081
          public_base: {$masIssuer}/
          issuer: {$masIssuer}/
        database:
          uri: {$db}
        email:
          from: '"Authentication Service" <root@localhost>'
          reply_to: '"Authentication Service" <root@localhost>'
          transport: blackhole
        secrets:
          encryption: {$b['mas_encryption']}
          keys:
          - key: |
        {$rsa}
          - key: |
        {$ec}
        passwords:
          enabled: false
        matrix:
          kind: synapse
          homeserver: {$serverName}
          secret: {$b['mas_synapse_secret']}
          endpoint: http://matrix:8008/
        upstream_oauth2:
          providers:
          - id: {$b['provider_ulid']}
            human_name: Cosmopolitan Governance App
            issuer: {$issuer}
            client_id: {$b['client_id']}
            client_secret: {$b['oidc_client_secret']}
            token_endpoint_auth_method: client_secret_post
            scope: "openid profile"
            discovery_mode: oidc
            pkce_method: always
            claims_imports:
              subject:
                template: "{{ user.sub }}"
              localpart:
                action: require
                template: "{{ user.preferred_username }}"
              displayname:
                action: suggest
                template: "{{ user.preferred_username }}"
        YAML;
    }

    /** @param array<string,string> $b */
    private function report(array $b, string $issuer, string $masIssuer, string $serverName, bool $dryRun): void
    {
        $this->line('');
        $this->info('Matched secret bundle '.($dryRun ? '(print-only — nothing written)' : 'generated'));
        $this->line("  OIDC issuer (game)   : {$issuer}");
        $this->line("  MAS issuer           : {$masIssuer}");
        $this->line("  provider id (ULID)   : {$b['provider_ulid']}");
        $this->line("  MAS upstream redirect: {$b['redirect_uri']}");
        $this->line('');
        $this->comment('Apply these to the sibling config files (matrix:setup does not edit them — avoids YAML clobber):');
        $this->line("  docker/matrix/appservice/registration.yaml  as_token: {$b['as_token']}");
        $this->line("  docker/matrix/appservice/registration.yaml  hs_token: {$b['hs_token']}");
        $this->line("  docker/matrix/conf.d/20-mas.yaml             secret  : {$b['mas_synapse_secret']}  (== MAS matrix.secret)");
        $this->line("  docker/livekit/livekit.yaml                  key/sec : {$b['livekit_key']} / {$b['livekit_secret']}");
    }

    private function pem(array $opts): string
    {
        $res = openssl_pkey_new($opts);
        if ($res === false) {
            throw new RuntimeException('openssl key generation failed (ext-openssl required).');
        }
        openssl_pkey_export($res, $pem);

        return (string) $pem;
    }

    /** Indent each PEM line by 6 spaces for the YAML block scalar under `key: |`. */
    private function indentPem(string $pem): string
    {
        $lines = preg_split('/\r?\n/', trim($pem)) ?: [];

        return implode("\n", array_map(fn (string $l) => '      '.$l, $lines));
    }

    /** @param array<string,string> $kv */
    private function upsertEnv(string $path, array $kv): void
    {
        $contents = is_file($path) ? (string) file_get_contents($path) : '';
        foreach ($kv as $key => $value) {
            $line = $key.'='.$this->envValue($value);
            $pattern = '/^'.preg_quote($key, '/').'=.*$/m';
            if (preg_match($pattern, $contents)) {
                $contents = (string) preg_replace($pattern, $line, $contents);
            } else {
                $contents = rtrim($contents, "\n")."\n".$line."\n";
            }
        }
        $this->writeFile($path, $contents);
    }

    private function envValue(string $value): string
    {
        // Quote anything that isn't a bare token (URLs carry ://, lists carry commas).
        return preg_match('/^[A-Za-z0-9_]+$/', $value) ? $value : '"'.$value.'"';
    }

    private function writeFile(string $path, string $contents): void
    {
        $dir = dirname($path);
        if (! is_dir($dir) && ! @mkdir($dir, 0755, true) && ! is_dir($dir)) {
            throw new RuntimeException("Could not create directory {$dir}.");
        }
        if (file_put_contents($path, $contents) === false) {
            throw new RuntimeException("Could not write {$path}.");
        }
    }
}
