<!DOCTYPE html>
@php
    $locale = str_replace('_', '-', app()->getLocale());
    // Direction comes from THE locale registry (config/locales.php, generated by
    // scripts/i18n/languages.py). This was a hand-kept list of ['ar','fa','he','ur']
    // — the fifth copy of the locale list, and the only one naming locales that
    // existed nowhere else. It was also missing Dhivehi and Pashto, both RTL.
    $dir = data_get(config('locales.locales'), $locale . '.dir', 'ltr');

    // Preload the two latin Instrument Sans faces (regular + semibold) that
    // paint the first screen — fonts.css carries font-display: swap, so this
    // removes the FOUT window for body text and headings. Guarded: the woff2
    // files are manifest-tracked via cga/fonts.css url() references, but a
    // stale/partial build must never take the page down over a hint.
    try {
        $preloadFonts = [
            \Illuminate\Support\Facades\Vite::asset('resources/fonts/instrument-sans-400-latin.woff2'),
            \Illuminate\Support\Facades\Vite::asset('resources/fonts/instrument-sans-600-latin.woff2'),
        ];
    } catch (\Throwable $e) {
        $preloadFonts = [];
    }
@endphp
<html lang="{{ $locale }}" dir="{{ $dir }}">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
        <meta name="csrf-token" content="{{ csrf_token() }}" />
        {{-- Visible even while the frontend modules are still downloading. --}}
        <style>
            #initial-page-loading { position: fixed; inset: 0 0 auto; z-index: 10000; padding: .6rem .8rem; text-align: end; color: #fff; background: #101827; font: 14px system-ui, sans-serif; border-top: 3px solid #f6c453; }
            #initial-page-loading a { margin-inline-start: .75rem; color: #f6c453; }
        </style>
        @foreach ($preloadFonts as $font)
        <link rel="preload" href="{{ $font }}" as="font" type="font/woff2" crossorigin />
        @endforeach
        @vite(['resources/css/app.css', 'resources/js/app.js'])
        @inertiaHead
    </head>
    <body>
        <div id="initial-page-loading" role="status">{{ __('Loading…') }}</div>
        @inertia
    </body>
</html>
