<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * Phase F — per-request locale resolution. Sets the app locale so BOTH the
 * Inertia shared `locale` prop AND the blade <html lang/dir> (which read
 * app()->getLocale()) agree on first paint. Resolution order:
 *   1. the authenticated user's stored locale,
 *   2. a guest's session choice (POST /locale),
 *   3. Accept-Language negotiated against the supported product locales,
 *   4. English.
 * Registered BEFORE HandleInertiaRequests. `en-XA` (the pseudo-locale QA tool)
 * is never resolved server-side — it is a client-only dev toggle.
 */
class SetLocale
{
    /**
     * Supported product locales — resolved from THE locale registry
     * (config/locales.php, generated by scripts/i18n/languages.py alongside the
     * JS registry). This constant used to be a hand-copy of the JS list, and
     * "mirrors" was doing a lot of unearned work: five copies of this list
     * existed and had already drifted.
     *
     * "Supported" means ENABLED — a catalog exists. Registered-but-display-only
     * locales are deliberately not resolvable server-side: negotiating a user
     * into a locale with no messages renders English with none of the fallback
     * signalling, which reads as a bug rather than an honest gap.
     *
     * @return list<string>
     */
    public static function supported(): array
    {
        $locales = config('locales.locales', []);

        $enabled = array_keys(array_filter(
            $locales,
            static fn (array $l): bool => (bool) ($l['enabled'] ?? false),
        ));

        /* Fail safe, never closed: an unreadable registry must not make the app
           monolingual mid-request. */
        return $enabled !== [] ? $enabled : ['en'];
    }

    public function handle(Request $request, Closure $next): Response
    {
        $locale = $this->resolve($request);

        app()->setLocale($locale);

        return $next($request);
    }

    private function resolve(Request $request): string
    {
        $user = $request->user();
        if ($user !== null && $this->isSupported($user->locale)) {
            return (string) $user->locale;
        }

        $session = $request->hasSession() ? $request->session()->get('locale') : null;
        if ($this->isSupported($session)) {
            return (string) $session;
        }

        $negotiated = $this->negotiate((string) $request->header('Accept-Language', ''));
        if ($negotiated !== null) {
            return $negotiated;
        }

        return 'en';
    }

    private function isSupported(?string $locale): bool
    {
        return $locale !== null && in_array($locale, self::supported(), true);
    }

    /** Map the highest-q Accept-Language tag onto a supported locale. */
    private function negotiate(string $header): ?string
    {
        foreach (explode(',', $header) as $part) {
            $tag = strtolower(trim(explode(';', $part)[0]));
            if ($tag === '') {
                continue;
            }
            if (str_starts_with($tag, 'zh')) {
                return 'zh-Hans';
            }
            $primary = explode('-', $tag)[0];
            foreach (self::supported() as $supported) {
                if ($primary === strtolower(explode('-', $supported)[0])) {
                    return $supported;
                }
            }
        }

        return null;
    }
}
