/* GENERATED from manifest.json - regenerate with the snippet in MANIFEST.md. */
window.CGA_MANIFEST = [
 {
  "file": "index.html",
  "title": "Launchpad — the five interaction classes + journey directory",
  "interactionClass": "all",
  "journeys": [],
  "reusesV1": [
   "index.html"
  ],
  "productionPages": [],
  "matrix": [],
  "forms": [],
  "status": "built-layer",
  "stage": 0,
  "notes": "v2 entry point. The five interaction classes as cards, the journey directory with progress rails, the eight Live-Room variants, and handoff links. Governance register; reuses v1 tokens/shell foundation via fixtures-v2 + shell-v2."
 },
 {
  "file": "tour.html",
  "title": "Guided tour — the linear walkthrough",
  "module": "shared",
  "interactionClass": "all",
  "journeys": [],
  "reusesV1": [],
  "productionPages": [],
  "matrix": [],
  "forms": [],
  "status": "built-layer",
  "stage": 0,
  "notes": "One linear path through the whole game layer (35 stops, 8 acts). A page enters tour mode via ?step=N; shell-v2 renders a Back/Next follow-along bar at the top of <main>. The order is exposed as CGA.shellV2.tour and is the spine of this page."
 },
 {
  "file": "shared/live-room.html",
  "title": "Live Civic Room — the keystone (8 variants via ?variant=)",
  "interactionClass": "all",
  "journeys": [
   "election",
   "committee-session",
   "bill",
   "court-case",
   "budget",
   "start-org",
   "board-meeting",
   "form-a-group",
   "mutual-aid",
   "petition-to-referendum",
   "public-service",
   "stipend-and-tax",
   "two-governments"
  ],
  "reusesV1": [
   "legislature/session-console.html",
   "legislature/committee-detail.html",
   "judiciary/case-detail.html",
   "organizations/board-elections.html",
   "electoral/open-ballot.html",
   "legislature/referendums.html"
  ],
  "productionPages": [
   "resources/js/Pages/Legislature/SessionConsole.vue",
   "resources/js/Components/Legislature/VoteTally.vue",
   "resources/js/Components/Legislature/AgendaStrip.vue",
   "resources/js/Pages/Civic/MatrixCommons.vue",
   "resources/js/Pages/Judiciary/CaseDetail.vue",
   "resources/js/Pages/Organizations/BoardElections.vue"
  ],
  "matrix": [
   "social_spaces(halls)",
   "matrix_rooms",
   "LiveKitTokenService",
   "TestimonyBridgeService",
   "TranslationGate",
   "MatrixPostingGateService"
  ],
  "forms": [
   "F-SPK-001..009",
   "F-CHR-001..004",
   "F-LEG-002..007",
   "F-JDG-001..003",
   "F-ORG-003..004",
   "F-SOC-001..002"
  ],
  "status": "built-layer",
  "stage": 1,
  "configContract": "MANIFEST.md §Live-Room config contract",
  "notes": "THE keystone. The fused form+social surface: header band + countdown clocks, locked/unlocked agenda, center-stage floor with How-this-works drawer + v1 deep-link, the vote tile (denominator always visible), the speaker rail (presence, hands-raised queue, Matrix chat with seat badges + testimony, voice, the translation privacy rail), the testimony-bridge record strip. Chair controls go live when you assume the chair persona; aria-live announces floor/vote/result. Eight variants: committee, legislative, exec, board, court, forum, townhall, group."
 },
 {
  "file": "shared/coverage.html",
  "title": "v2 coverage — meeting types × journeys × interaction classes × mechanics",
  "interactionClass": "all",
  "journeys": [],
  "reusesV1": [],
  "productionPages": [],
  "matrix": [],
  "forms": [],
  "status": "built-layer",
  "stage": 1,
  "notes": "Generated from the v2 manifest + fixtures.v2. Proves §13 definition-of-done as stages land."
 },
 {
  "file": "journeys/journey.html",
  "title": "Journey — guided arc (13 journeys via ?id=)",
  "module": "journeys",
  "interactionClass": "all",
  "journeys": [],
  "reusesV1": [],
  "productionPages": [],
  "matrix": [],
  "forms": [],
  "status": "built-layer",
  "stage": 2,
  "notes": "One page renders every journey from ?id=: the progress rail, now/your-part/next, the live rooms it passes through, and the v1 deep-links for the formal steps."
 },
 {
  "file": "economy/economy-home.html",
  "title": "The exchange — the economy home",
  "module": "economy",
  "interactionClass": "all",
  "journeys": [],
  "reusesV1": [],
  "productionPages": [],
  "matrix": [],
  "forms": [],
  "status": "planned-layer",
  "stage": 2,
  "notes": "Entry to the Open Market: marketplace, requests, agreements, wallet, joint ledgers, units/monetary policy, stipend, treasury, org economics. The economic clock + the rails."
 },
 {
  "file": "economy/marketplace.html",
  "title": "Marketplace — offers on the Open Market",
  "module": "economy",
  "interactionClass": "all",
  "journeys": [],
  "reusesV1": [],
  "productionPages": [],
  "matrix": [],
  "forms": [],
  "status": "planned-layer",
  "stage": 2,
  "notes": "Listings (goods/services); CGC identical-terms; place an order; offer<->request switch. F-IND-021/022."
 },
 {
  "file": "economy/listing-detail.html",
  "title": "Listing detail",
  "module": "economy",
  "interactionClass": "all",
  "journeys": [],
  "reusesV1": [],
  "productionPages": [],
  "matrix": [],
  "forms": [],
  "status": "planned-layer",
  "stage": 2,
  "notes": "One listing; the order flow forms an agreement; private settlement."
 },
 {
  "file": "economy/requests.html",
  "title": "Request board — the mirror",
  "module": "economy",
  "interactionClass": "all",
  "journeys": [],
  "reusesV1": [],
  "productionPages": [],
  "matrix": [],
  "forms": [],
  "status": "planned-layer",
  "stage": 2,
  "notes": "Work board (F-IND-019 -> F-IND-014 -> co-determination) + mutual-aid/assistance (private). Offer<->Request."
 },
 {
  "file": "economy/request-detail.html",
  "title": "Work posting detail",
  "module": "economy",
  "interactionClass": "all",
  "journeys": [],
  "reusesV1": [],
  "productionPages": [],
  "matrix": [],
  "forms": [],
  "status": "planned-layer",
  "stage": 2,
  "notes": "Application -> F-IND-014 -> org_contract -> crosses the worker-seat threshold."
 },
 {
  "file": "economy/wallet.html",
  "title": "My wallet — private",
  "module": "economy",
  "interactionClass": "all",
  "journeys": [],
  "reusesV1": [],
  "productionPages": [],
  "matrix": [],
  "forms": [],
  "status": "planned-layer",
  "stage": 2,
  "notes": "Personal balance + transactions; never federated, like a ballot; abstract units; F-IND-023 transfer."
 },
 {
  "file": "economy/joint-ledgers.html",
  "title": "Joint ledgers — agreement-gated",
  "module": "economy",
  "interactionClass": "all",
  "journeys": [],
  "reusesV1": [],
  "productionPages": [],
  "matrix": [],
  "forms": [],
  "status": "planned-layer",
  "stage": 2,
  "notes": "Co-owned accounts; movements need every signer to agree. Art. V §2 + Art. I."
 },
 {
  "file": "economy/units.html",
  "title": "Units & monetary policy",
  "module": "economy",
  "interactionClass": "all",
  "journeys": [],
  "reusesV1": [],
  "productionPages": [],
  "matrix": [],
  "forms": [],
  "status": "planned-layer",
  "stage": 2,
  "notes": "The unit + subdivisions (measurement standards), worth, and the dual-door monetary levers (F-LEG-031). Art. V §5."
 },
 {
  "file": "economy/stipend.html",
  "title": "Civic stipend — UBI + role differential",
  "module": "economy",
  "interactionClass": "all",
  "journeys": [],
  "reusesV1": [],
  "productionPages": [],
  "matrix": [],
  "forms": [],
  "status": "planned-layer",
  "stage": 2,
  "notes": "base (residency floor) + capped role bumps (operator/moderator/officeholder) on the economic clock; dual-door; k-anon. F-TRE-004."
 },
 {
  "file": "economy/treasury.html",
  "title": "Public finance — the public ledger",
  "module": "economy",
  "interactionClass": "all",
  "journeys": [],
  "reusesV1": [],
  "productionPages": [],
  "matrix": [],
  "forms": [],
  "status": "planned-layer",
  "stage": 2,
  "notes": "Budget cycle (F-LEG-037/038, F-TRE-001..003), public double-entry hash-chained ledger, revenue, borrowing. Art. II §9, III §4, V §4."
 },
 {
  "file": "economy/agreements.html",
  "title": "Instruments of agreement",
  "module": "economy",
  "interactionClass": "all",
  "journeys": [],
  "reusesV1": [],
  "productionPages": [],
  "matrix": [],
  "forms": [],
  "status": "planned-layer",
  "stage": 2,
  "notes": "Contracts (labor/ownership/joint/sale) each with the Supremacy-of-Rights floor. Art. I."
 },
 {
  "file": "economy/agreement-detail.html",
  "title": "Agreement detail",
  "module": "economy",
  "interactionClass": "all",
  "journeys": [],
  "reusesV1": [],
  "productionPages": [],
  "matrix": [],
  "forms": [],
  "status": "planned-layer",
  "stage": 2,
  "notes": "One agreement; both-parties-sign; the constitutional floor; co-determination consequence."
 },
 {
  "file": "economy/org-settings.html",
  "title": "Organization economics",
  "module": "economy",
  "interactionClass": "all",
  "journeys": [],
  "reusesV1": [],
  "productionPages": [],
  "matrix": [],
  "forms": [],
  "status": "planned-layer",
  "stage": 2,
  "notes": "Org settings, shares + fair-market (Art. III §5), dues, the org ledger, taxes. Inter-org units."
 },
 {
  "file": "social/profile.html",
  "title": "Personal profile",
  "module": "social",
  "interactionClass": "all",
  "journeys": [],
  "reusesV1": [],
  "productionPages": [],
  "matrix": [],
  "forms": [],
  "status": "built-layer",
  "stage": 2,
  "notes": "Social profile: bio, endorsements (public by choice), groups, orgs, achievements (Proposed), follow/message. Pseudonymity. Art. I."
 },
 {
  "file": "social/org-profile.html",
  "title": "Organization profile",
  "module": "social",
  "interactionClass": "all",
  "journeys": [],
  "reusesV1": [],
  "productionPages": [],
  "matrix": [],
  "forms": [],
  "status": "built-layer",
  "stage": 2,
  "notes": "Org public page: type/charter/workers/board/co-determination/listings/contracts/ledger."
 },
 {
  "file": "social/rep.html",
  "title": "Your representative (rep<->citizen)",
  "module": "social",
  "interactionClass": "all",
  "journeys": [],
  "reusesV1": [],
  "productionPages": [],
  "matrix": [],
  "forms": [],
  "status": "built-layer",
  "stage": 2,
  "notes": "A rep public page: record, forum, office hours, request a meeting, constituent message, the requests queue. Art. I Fair Representation."
 },
 {
  "file": "social/social-home.html",
  "title": "Social — the network home",
  "module": "social",
  "interactionClass": "all",
  "journeys": [],
  "reusesV1": [],
  "productionPages": [],
  "matrix": [],
  "forms": [],
  "status": "built-layer",
  "stage": 2,
  "notes": "Public square + halls entry, a feed, follows; uncensorable + pseudonymity. Art. I."
 },
 {
  "file": "civic/today.html",
  "title": "Today — what is live now",
  "module": "civic",
  "interactionClass": "all",
  "journeys": [],
  "reusesV1": [],
  "productionPages": [],
  "matrix": [],
  "forms": [],
  "status": "built-layer",
  "stage": 2,
  "notes": "One-tap entries to live sessions/hearings/votes/forums/stipend/group meetings in my jurisdictions."
 },
 {
  "file": "civic/my-civic-life.html",
  "title": "My civic life",
  "module": "civic",
  "interactionClass": "all",
  "journeys": [],
  "reusesV1": [],
  "productionPages": [],
  "matrix": [],
  "forms": [],
  "status": "built-layer",
  "stage": 2,
  "notes": "Personal home base: groups, orgs, open votes, record, rep, wallet (Planned), stipend (Planned), achievements (Proposed)."
 },
 {
  "file": "groups/groups-home.html",
  "title": "Informal groups — browse & create",
  "module": "groups",
  "interactionClass": "all",
  "journeys": [],
  "reusesV1": [],
  "productionPages": [],
  "matrix": [],
  "forms": [],
  "status": "built-layer",
  "stage": 3,
  "notes": "Voluntary affinity groups (Art. I); browse/join + create. No governance power; membership private."
 },
 {
  "file": "groups/group-create.html",
  "title": "Create a group",
  "module": "groups",
  "interactionClass": "all",
  "journeys": [],
  "reusesV1": [],
  "productionPages": [],
  "matrix": [],
  "forms": [],
  "status": "built-layer",
  "stage": 3,
  "notes": "Two-step create: name, purpose, open/invite, spin up a room. No charter, no power conferred."
 },
 {
  "file": "groups/group-detail.html",
  "title": "Group home",
  "module": "groups",
  "interactionClass": "all",
  "journeys": [],
  "reusesV1": [],
  "productionPages": [],
  "matrix": [],
  "forms": [],
  "status": "built-layer",
  "stage": 3,
  "notes": "A group: discussion room, members, pinned, call a meeting (casual/facilitated/formal via the live room), public-square carve-outs vs private self-moderation, optional next steps (org/petition)."
 },
 {
  "file": "social/legitimacy.html",
  "title": "Reach & legitimacy gauge",
  "module": "social",
  "interactionClass": "all",
  "journeys": [],
  "reusesV1": [],
  "productionPages": [],
  "matrix": [],
  "forms": [],
  "status": "planned-layer",
  "stage": 3,
  "notes": "Phase I reach ratio (verified/population), k-anon, display-only — NEVER a governance input (CI-1). Activation tiers."
 },
 {
  "file": "operator/operator-home.html",
  "title": "Run a node — the operator plane",
  "module": "operator",
  "interactionClass": "operator",
  "journeys": [],
  "reusesV1": [
   "jurisdictions/federation.html"
  ],
  "productionPages": [
   "resources/js/Pages/Jurisdictions/Federation.vue"
  ],
  "matrix": [],
  "forms": [],
  "status": "built-layer",
  "stage": "G",
  "notes": "Off the constitutional plane (capability, not role). The plane wall, the 4 named roles, the health line, entry to every operator surface. Operators = de-facto board answerable to the seated government."
 },
 {
  "file": "operator/setup.html",
  "title": "Set up your node — first-run wizard",
  "module": "operator",
  "interactionClass": "operator",
  "journeys": [],
  "reusesV1": [
   "jurisdictions/federation.html"
  ],
  "productionPages": [
   "resources/js/Pages/Jurisdictions/Federation.vue"
  ],
  "matrix": [],
  "forms": [],
  "status": "built-layer",
  "stage": "G",
  "notes": "Claim an operator account (local password OR device-key link), name the instance, pick a role (Record Keeper recommended), role-specific setup, done. Governed roles can only be requested → dual-meter approval."
 },
 {
  "file": "operator/console.html",
  "title": "The operator console (two-tier)",
  "module": "operator",
  "interactionClass": "operator",
  "journeys": [],
  "reusesV1": [
   "jurisdictions/federation.html"
  ],
  "productionPages": [
   "resources/js/Pages/Jurisdictions/Federation.vue"
  ],
  "matrix": [],
  "forms": [],
  "status": "built-layer",
  "stage": "G",
  "notes": "Tier 1: 4 named-role cards + the peers/sync health line. Tier 2 (Advanced): the raw 9-channel grid, Meters A/B/C, peers, sync ledger, transports, CLI. Federation.vue redesign."
 },
 {
  "file": "operator/roles.html",
  "title": "Roles & channels",
  "module": "operator",
  "interactionClass": "operator",
  "journeys": [],
  "reusesV1": [
   "jurisdictions/federation.html"
  ],
  "productionPages": [
   "resources/js/Pages/Jurisdictions/Federation.vue"
  ],
  "matrix": [],
  "forms": [],
  "status": "built-layer",
  "stage": "G",
  "notes": "The 4 named roles over the 9 capability channels (3 self-asserted / 6 governed); the qualify→request→approve→join lifecycle; the three meters (B supersedes A; C future)."
 },
 {
  "file": "operator/mesh.html",
  "title": "Mesh & federation",
  "module": "operator",
  "interactionClass": "operator",
  "journeys": [],
  "reusesV1": [
   "jurisdictions/federation.html"
  ],
  "productionPages": [
   "resources/js/Pages/Jurisdictions/Federation.vue"
  ],
  "matrix": [],
  "forms": [],
  "status": "built-layer",
  "stage": "G",
  "notes": "Join a cluster (4-step wizard), peers (ESM-20), Full Faith & Credit sync, authority + the Art. V §7 read-write petition (government decides, not the operator), transports."
 },
 {
  "file": "operator/dns.html",
  "title": "DNS & certificates (Identity Broker)",
  "module": "operator",
  "interactionClass": "operator",
  "journeys": [],
  "reusesV1": [
   "jurisdictions/federation.html"
  ],
  "productionPages": [
   "resources/js/Pages/Jurisdictions/Federation.vue"
  ],
  "matrix": [],
  "forms": [],
  "status": "built-layer",
  "stage": "G",
  "notes": "DNS-before-cert; per-name primary + wildcard backup (gated/stub); DDNS; DNS providers (Cloudflare live, stubs); the LE budget pre-flight. Token write-only, never federates. services/mesh-cert-broker."
 },
 {
  "file": "operator/identity.html",
  "title": "Identity (G-ID)",
  "module": "operator",
  "interactionClass": "operator",
  "journeys": [],
  "reusesV1": [
   "jurisdictions/federation.html"
  ],
  "productionPages": [
   "resources/js/Pages/Jurisdictions/Federation.vue"
  ],
  "matrix": [],
  "forms": [],
  "status": "built-layer",
  "stage": "G",
  "notes": "Operator devices + mesh identity (link by possession, never password replay); citizen attestation + AttestedForwardedActor (attestation + action-signature + subject checks); the expiry sweep. Plane wall."
 },
 {
  "file": "operator/moderation.html",
  "title": "Moderation & the legal floor",
  "module": "operator",
  "interactionClass": "operator",
  "journeys": [],
  "reusesV1": [
   "jurisdictions/federation.html"
  ],
  "productionPages": [
   "resources/js/Pages/Jurisdictions/Federation.vue"
  ],
  "matrix": [],
  "forms": [],
  "status": "built-layer",
  "stage": "G",
  "notes": "The legitimacy flip (operator relay below → judicial above, automatic), the four carve-outs (viewpoint removal has no code path), M-5 legal floor (key-possession, closed legal_basis enum, never server_acl, F-SOC-004)."
 },
 {
  "file": "operator/versioning.html",
  "title": "Versions & upgrades",
  "module": "operator",
  "interactionClass": "operator",
  "journeys": [],
  "reusesV1": [
   "jurisdictions/federation.html"
  ],
  "productionPages": [
   "resources/js/Pages/Jurisdictions/Federation.vue"
  ],
  "matrix": [],
  "forms": [],
  "status": "built-layer",
  "stage": "G",
  "notes": "The hardened admissibility filter (Art. VII), the dual-meter upgrade agreement, the game-in-progress freeze (Art. II §7), peer version match/refusal (fail-closed)."
 },
 {
  "file": "shared/video-player.html",
  "title": "Video library — the multi-track player",
  "module": "learn",
  "interactionClass": "all",
  "journeys": [],
  "reusesV1": [],
  "productionPages": [],
  "matrix": [],
  "forms": [],
  "status": "built-layer",
  "stage": "K",
  "notes": "The reusable multi-track player modeled on functions/video_player.php: one silent master MP4 + N audio (.m4a) + N caption (.vtt) tracks, the link toggle, drift-correction, remembered prefs. The library of every guide video. components-v2.js videoPlayer/initVideo."
 },
 {
  "file": "learn/learn-home.html",
  "title": "Learn — education tracks",
  "module": "learn",
  "interactionClass": "all",
  "journeys": [],
  "reusesV1": [],
  "productionPages": [],
  "matrix": [],
  "forms": [],
  "status": "built-layer",
  "stage": "K",
  "notes": "The education home: six tracks (getting started, elections, lawmaking, justice, economy, running a node), a featured lesson with the video player, and progress. Every lesson wraps a video + its SOP + a knowledge check + the live journey."
 },
 {
  "file": "learn/lesson.html",
  "title": "Lesson — video + SOP + check",
  "module": "learn",
  "interactionClass": "all",
  "journeys": [],
  "reusesV1": [],
  "productionPages": [],
  "matrix": [],
  "forms": [],
  "status": "built-layer",
  "stage": "K",
  "notes": "One lesson via ?id= (or ?sop=): the multi-track video, the standard procedure, a knowledge check, and a deep-link to the live journey and the v1 formal screen."
 },
 {
  "file": "learn/guides.html",
  "title": "Guides & procedures — the SOP index",
  "module": "learn",
  "interactionClass": "all",
  "journeys": [],
  "reusesV1": [],
  "productionPages": [],
  "matrix": [],
  "forms": [],
  "status": "built-layer",
  "stage": "K",
  "notes": "The SOP-in-interface once-over surface: every journey/tool/workflow's standard operating procedure, searchable by module, each with its video and report-an-issue."
 },
 {
  "file": "translation/translation-home.html",
  "title": "Translation status — languages x modalities",
  "module": "translation",
  "interactionClass": "all",
  "journeys": [],
  "reusesV1": [],
  "productionPages": [],
  "matrix": [],
  "forms": [],
  "status": "built-layer",
  "stage": "N",
  "notes": "The coverage matrix: 24 curated of 115 mapped languages (77 shipped), six modalities (interface, page copy, video audio, captions, education, help), the AI-first-round -> in-review -> community-verified -> published lifecycle, the engine, and add-a-language."
 },
 {
  "file": "translation/language.html",
  "title": "Language detail — review & verify",
  "module": "translation",
  "interactionClass": "all",
  "journeys": [],
  "reusesV1": [],
  "productionPages": [],
  "matrix": [],
  "forms": [],
  "status": "built-layer",
  "stage": "N",
  "notes": "One language via ?code=: per-modality breakdown, the review queue (source + AI draft -> accept/correct -> quorum), the contributor leaderboard, and the rail that verification is gated to people who read the interface in that language."
 },
 {
  "file": "support/support-home.html",
  "title": "Help & support — the hub",
  "module": "support",
  "interactionClass": "all",
  "journeys": [],
  "reusesV1": [],
  "productionPages": [],
  "matrix": [],
  "forms": [],
  "status": "built-layer",
  "stage": "ops",
  "notes": "The help hub: report an issue, the ticket queue, the guides/SOPs, the translation interface, and how a report routes itself by category."
 },
 {
  "file": "support/report.html",
  "title": "Report an issue",
  "module": "support",
  "interactionClass": "all",
  "journeys": [],
  "reusesV1": [],
  "productionPages": [],
  "matrix": [],
  "forms": [],
  "status": "built-layer",
  "stage": "ops",
  "notes": "The site-wide report form (linked from every footer): pick a category (bug/translation/accessibility/content/abuse/idea), the page is attached automatically, and the report routes itself - abuse/illegal goes OFF to the moderation & legal plane, never adjudicated here."
 },
 {
  "file": "support/tickets.html",
  "title": "Tickets — the queue",
  "module": "support",
  "interactionClass": "all",
  "journeys": [],
  "reusesV1": [],
  "productionPages": [],
  "matrix": [],
  "forms": [],
  "status": "built-layer",
  "stage": "ops",
  "notes": "The ticket queue: filter by status/category, severity dots, routing (bugs->operators, translation->translators, abuse->moderation plane). Open counts and the lifecycle."
 },
 {
  "file": "support/ticket.html",
  "title": "Ticket detail",
  "module": "support",
  "interactionClass": "all",
  "journeys": [],
  "reusesV1": [],
  "productionPages": [],
  "matrix": [],
  "forms": [],
  "status": "built-layer",
  "stage": "ops",
  "notes": "One ticket via ?id=: the report, the routing, the status thread, linked translation review or moderation carve-out where relevant."
 }
];
