#!/usr/bin/env node
/* ============================================================================
   K-2 — build_education_payload.mjs (lane 15, V3 synthesis Wave 1, slice L1/L4)

   THE education corpus lives in docs/plans/education/K2_CONTENT_*.md — authored
   Markdown, operator-approved template (K2_CURRICULUM.md §9). This script is
   the ONLY way that corpus reaches the app. Everything it writes is GENERATED:
   edit the corpus (or the catalog/library), re-run this, commit both.

     node scripts/education/build_education_payload.mjs

   Outputs (all overwritten in full):
     resources/js/i18n/locales/en/c_education.json     482+ strings, flat
                                     `education_{surface_snake}.{part}` keys
     resources/js/i18n/meta/en/c_education.json        lane-5 meta shape
     resources/js/i18n/locales/en/c_achievements.json  141 award titles keyed
                                     by the EXACT title_key the ledger stores
     resources/js/i18n/meta/en/c_achievements.json
     resources/js/registry/education.js                EDUCATION_BY_SURFACE —
                                     i18n keys + literal cites, per surface id
     resources/js/registry/flows.js                    FLOWS_BY_SURFACE — the
                                     mockups' 80-workflow "where this fits"
                                     context, remapped to app surface ids

   Sources of truth (read, never written):
     docs/plans/education/K2_CONTENT_*.md              the authored corpus
     app/Domain/Achievements/AchievementCatalog.php    award key -> title_key
     docs/plans/education/K2_ACHIEVEMENT_LIBRARY.md    ACH-* English titles
     config/cga/journeys.php                           tour-arc English titles
     config/cga/surfaces.php                           surface-id cross-check
     mockups/v3/assets/js/fixtures-flows.js            flow context (itself
                                     generated by mockups/v3/tools/gen_flow_context.py)

   RAILS: no answer keys, no correct_keys, nothing graded — this is display
   copy only (the graded half is server-side by K2_ENGINE_PLAN §2/§8). The
   `cite` column is NEVER emitted as a translatable string: Article/form/role
   tokens are identical in every language, so cites ride the registry as
   literals. Any cross-check failure exits 1 — a payload that silently drops
   a surface would read as "covered" when it is not.
   ============================================================================ */

import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const rel = (...p) => path.join(ROOT, ...p);
const read = (...p) => fs.readFileSync(rel(...p), 'utf8');

const sha256 = (s) => crypto.createHash('sha256').update(s, 'utf8').digest('hex');
const surfaceSnake = (id) => id.replace(/[/-]/g, '_');

let failures = 0;
const fail = (msg) => { console.error('  ✗ ' + msg); failures++; };
const note = (msg) => console.log('  ' + msg);

/* ── 1. Parse the corpus markdown ─────────────────────────────────────────
   Section grammar (K2_CURRICULUM §9, as authored in K2_CONTENT_SURFACES.md):
     ### <n>. `<surface/id>` — <Title>
     **learn:** <sentence, may wrap>
     | # | do | detail | cite |   (0..n data rows: | 1 | ... | ... | ... |)
     > **The why:** <callout, may wrap over > lines>     (optional)
*/
function stripMd(s) {
    return s
        .replace(/^\*\([^)]*\)\*\s*/, '')       // leading *(doc annotation)*
        .replace(/\*/g, '')
        .replace(/`/g, '')
        .replace(/\s+/g, ' ')
        .trim();
}

function parseCorpus(file) {
    const lines = read(file).split(/\r?\n/);
    const surfaces = [];
    let cur = null, mode = null;

    const flush = () => { if (cur) surfaces.push(cur); cur = null; mode = null; };

    for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        const head = line.match(/^### \d+\.\s+`([^`]+)`\s+—\s+(.+)$/);
        if (head) {
            flush();
            cur = { id: head[1], title: stripMd(head[2]), learn: '', steps: [], why: '', line: i + 1 };
            mode = null;
            continue;
        }
        if (!cur) continue;

        if (/^## /.test(line)) { flush(); continue; }    // next wave heading

        const learn = line.match(/^\*\*learn:\*\*\s*(.*)$/);
        if (learn) { cur.learn = learn[1]; cur.learnLine = i + 1; mode = 'learn'; continue; }

        const row = line.match(/^\|\s*(\d+)\s*\|(.*)\|(.*)\|(.*)\|\s*$/);
        if (row) {
            const cite = stripMd(row[4]);
            cur.steps.push({
                n: Number(row[1]),
                do: stripMd(row[2]),
                detail: stripMd(row[3]),
                cite: cite === '—' || cite === '' ? null : cite,
                line: i + 1,
            });
            mode = 'table';
            continue;
        }

        const why = line.match(/^>\s*\*\*The why:\*\*\s*(.*)$/);
        if (why) { cur.why = why[1]; cur.whyLine = i + 1; mode = 'why'; continue; }

        if (mode === 'learn' && line.trim() !== '' && !line.startsWith('|') && !line.startsWith('>') && !line.startsWith('#') && !line.startsWith('---') && !line.startsWith('*(')) {
            cur.learn += ' ' + line.trim();
            continue;
        }
        if (mode === 'why' && line.startsWith('>')) {
            cur.why += ' ' + line.replace(/^>\s?/, '').trim();
            continue;
        }
        if (line.trim() === '' || line.startsWith('---')) { if (mode !== null) mode = null; }
    }
    flush();

    for (const s of surfaces) {
        s.learn = stripMd(s.learn);
        s.why = stripMd(s.why);
        if (!s.learn) fail(`${s.id} (${path.basename(file)}:${s.line}) has no learn sentence`);
        const ns = s.steps.map((st) => st.n);
        ns.forEach((n, idx) => { if (n !== idx + 1) fail(`${s.id} step numbering is not 1..n (saw ${ns.join(',')})`); });
    }
    return surfaces;
}

const corpusFiles = fs.readdirSync(rel('docs/plans/education'))
    .filter((f) => /^K2_CONTENT_.*\.md$/.test(f))
    .sort();
let corpus = [];
for (const f of corpusFiles) {
    const parsed = parseCorpus(path.join('docs/plans/education', f));
    note(`${f}: ${parsed.length} surfaces`);
    for (const s of parsed) {
        const dup = corpus.find((c) => c.id === s.id);
        if (dup) fail(`surface ${s.id} authored twice (${f} and earlier)`);
        s.file = 'docs/plans/education/' + f;
    }
    corpus = corpus.concat(parsed);
}

/* ── 2. Cross-check against config/cga/surfaces.php ─────────────────────── */
const surfacesPhp = read('config/cga/surfaces.php');
const appSurfaceIds = new Set(
    [...surfacesPhp.matchAll(/^    '([a-z0-9/-]+)' => \[/gm)].map((m) => m[1]),
);
note(`config/cga/surfaces.php: ${appSurfaceIds.size} surface ids`);
for (const s of corpus) {
    if (!appSurfaceIds.has(s.id)) fail(`corpus surface ${s.id} has NO record in config/cga/surfaces.php — the join key is broken`);
}

/* ── 3. Emit c_education.json + meta + registry/education.js ────────────── */
const eduStrings = {};   // flat i18n key -> english
const eduMeta = {};
const registry = {};     // surface id -> {learn, steps[{do,detail,cite}], why}

for (const s of corpus.sort((a, b) => a.id.localeCompare(b.id))) {
    const g = 'education_' + surfaceSnake(s.id);
    const put = (part, value, line) => {
        const key = `${g}.${part}`;
        eduStrings[key] = value;
        eduMeta[key] = {
            source_hash: sha256(value),
            shape: 'static',
            file: s.file,
            line,
            status: 'source',
        };
        return 'c_education.' + key;
    };

    const entry = { learn: put('learn', s.learn, s.learnLine ?? s.line), steps: [], why: null };
    for (const st of s.steps) {
        entry.steps.push({
            do: put(`s${st.n}_do`, st.do, st.line),
            detail: put(`s${st.n}_detail`, st.detail, st.line),
            cite: st.cite,
        });
    }
    if (s.why) entry.why = put('why', s.why, s.whyLine ?? s.line);
    registry[s.id] = entry;
}

/* ── 4. Achievement titles: catalog keys × library/journeys titles ──────── */
const catalogPhp = read('app/Domain/Achievements/AchievementCatalog.php');
const catalogKeys = [...catalogPhp.matchAll(/'(ACH-[A-Z]+-\d+)' => \['title_key' => '([a-z0-9_.]+)'/g)]
    .map((m) => ({ code: m[1], titleKey: m[2] }));
const arcBlock = catalogPhp.match(/TOUR_ARCS = \[(.*?)\];/s);
if (!arcBlock) fail('AchievementCatalog.php: TOUR_ARCS block not found');
const arcKeys = [...(arcBlock?.[1] ?? '').matchAll(/'([a-z-]+)'/g)].map((m) => m[1]);

const libraryMd = read('docs/plans/education/K2_ACHIEVEMENT_LIBRARY.md');
const libTitles = {};
for (const m of libraryMd.matchAll(/^\|\s*`(ACH-[A-Z]+-\d+)`\s*\|\s*(.+?)\s*\|/gm)) {
    libTitles[m[1]] = stripMd(m[2]);
}

const journeysPhp = read('config/cga/journeys.php');
const arcTitles = {};
{
    // arcs look like:  'election' => [ 'title'  => 'An election, end to end',
    const arcRe = /'([a-z][a-z-]+)' => \[\s*'title'\s*=>\s*'((?:[^'\\]|\\.)*)'/g;
    for (const m of journeysPhp.matchAll(arcRe)) arcTitles[m[1]] = m[2].replace(/\\'/g, "'");
}

const achStrings = {};
const achMeta = {};
for (const { code, titleKey } of catalogKeys) {
    const title = libTitles[code];
    if (!title) { fail(`catalog entry ${code} has no English title row in K2_ACHIEVEMENT_LIBRARY.md`); continue; }
    achStrings[titleKey] = title;
    achMeta[titleKey] = {
        source_hash: sha256(title), shape: 'static',
        file: 'docs/plans/education/K2_ACHIEVEMENT_LIBRARY.md', status: 'source',
    };
}
let arcCount = 0;
for (const [arc, title] of Object.entries(arcTitles)) {
    if (!arcKeys.includes(arc)) continue;             // non-arc quoted keys never match TOUR_ARCS
    const titleKey = 'achievement.tour.' + arc.replace(/-/g, '_');
    achStrings[titleKey] = title;
    achMeta[titleKey] = {
        source_hash: sha256(title), shape: 'static',
        file: 'config/cga/journeys.php', status: 'source',
    };
    arcCount++;
}

/* ── 5. Flow context: mockup byScreen -> app surface ids ────────────────── */
const flowsSrc = read('mockups/v3/assets/js/fixtures-flows.js');
const flowsMatch = flowsSrc.match(/CGA\.fixtures\.flows = (.*);\n\}\(\)\);/s);
const { byScreen } = JSON.parse(flowsMatch[1]);

/* The mockup's screen vocabulary differs from the app's surface ids in a few
   named places (the electoral/ -> elections/ module rename is the settled
   one; the rest are 1:1 aliases). Everything not listed maps to itself. */
const SCREEN_ALIAS = {
    'civic/civic-home': 'civic/home',
    'civic/onboarding': 'auth/register',
    'civic/advocate-registration': 'judiciary/advocate-console', // F-IND-015 lives there in the app
    'electoral/election-detail': 'elections/detail',
    'electoral/election-board-console': 'elections/board-console',
    // APPROXIMATION, logged: the app has no separate browser surface — the
    // viewer is the nearest surface record the flyout can key on.
    'jurisdictions/jurisdiction-browser': 'jurisdictions/viewer',
};
const mapScreen = (sid) => {
    if (SCREEN_ALIAS[sid]) return SCREEN_ALIAS[sid];
    const renamed = sid.replace(/^electoral\//, 'elections/');
    return renamed;
};

const flowsBySurface = {};
const unmapped = [];
for (const [sid, rows] of Object.entries(byScreen)) {
    const appId = mapScreen(sid);
    if (!appSurfaceIds.has(appId)) { unmapped.push(`${sid} -> ${appId}`); continue; }
    flowsBySurface[appId] = (flowsBySurface[appId] ?? []).concat(rows.map((r) => ({
        wf: r.wf, wfName: r.wfName, familyLabel: r.familyLabel,
        total: r.total, minStep: r.minStep,
        trigger: r.trigger, terminal: r.terminal,
        steps: r.steps, // [{n, action, prev, next, branches}]
    })));
}
for (const rows of Object.values(flowsBySurface)) rows.sort((a, b) => a.minStep - b.minStep || a.wf.localeCompare(b.wf));
if (unmapped.length) note(`flow screens with no app surface (dropped, listed so nothing is silent): ${unmapped.join(', ')}`);

/* ── 6. Write everything ─────────────────────────────────────────────────── */
const sortKeys = (o) => Object.fromEntries(Object.entries(o).sort(([a], [b]) => a.localeCompare(b)));
const writeJson = (p, obj) => fs.writeFileSync(rel(p), JSON.stringify(sortKeys(obj), null, 2) + '\n');

const GEN_HEADER = `/* ============================================================================
   GENERATED — do not edit. scripts/education/build_education_payload.mjs
   Source: docs/plans/education/K2_CONTENT_*.md (the authored K-2 corpus).
   Values are i18n keys into locales/<locale>/c_education.json; \`cite\` values
   are LITERAL Article/form/role tokens — identical in every language, never
   translated (the K-2 i18n contract). Re-run the script after editing the
   corpus and commit the outputs together.
   ============================================================================ */\n`;

fs.mkdirSync(rel('resources/js/registry'), { recursive: true });
writeJson('resources/js/i18n/locales/en/c_education.json', eduStrings);
writeJson('resources/js/i18n/meta/en/c_education.json', eduMeta);
writeJson('resources/js/i18n/locales/en/c_achievements.json', achStrings);
writeJson('resources/js/i18n/meta/en/c_achievements.json', achMeta);

fs.writeFileSync(rel('resources/js/registry/education.js'),
    GEN_HEADER
    + '\nexport const EDUCATION_BY_SURFACE = '
    + JSON.stringify(registry, null, 4).replace(/"([a-z_]+)":/g, '$1:')
    + ';\n');

fs.writeFileSync(rel('resources/js/registry/flows.js'),
    `/* ============================================================================
   GENERATED — do not edit. scripts/education/build_education_payload.mjs
   The mockups' 80 workflow walkthroughs (fixtures-flows.js, itself generated
   by mockups/v3/tools/gen_flow_context.py), inverted per screen and remapped
   onto APP surface ids (electoral/ -> elections/ and the named aliases in the
   build script). The Learn flyout's "where this fits" block reads this.
   ============================================================================ */\n
export const FLOWS_BY_SURFACE = `
    + JSON.stringify(flowsBySurface, null, 2)
    + ';\n');

/* ── 7. The numbers, printed so drift is visible ─────────────────────────── */
const eduCount = Object.keys(eduStrings).length;
const learnCount = corpus.length;
const stepStrings = corpus.reduce((n, s) => n + s.steps.length * 2, 0);
const whyCount = corpus.filter((s) => s.why).length;
console.log('');
note(`c_education.json: ${eduCount} strings (${learnCount} learn + ${stepStrings} step + ${whyCount} why)`);
note(`c_achievements.json: ${Object.keys(achStrings).length} titles (${catalogKeys.length} ACH-* + ${arcCount} tour arcs)`);
note(`registry/education.js: ${Object.keys(registry).length} surfaces`);
note(`registry/flows.js: ${Object.keys(flowsBySurface).length} surfaces with flow context`);

if (catalogKeys.length + arcCount !== Object.keys(achStrings).length) fail('achievement key/title join lost entries');
if (failures) {
    console.error(`\n${failures} cross-check failure(s) — nothing should ship from this run.`);
    process.exit(1);
}
console.log('\nOK.');
