<?php

namespace Tests\Feature;

use App\Support\MediaMeta;
use Inertia\Testing\AssertableInertia as Assert;
use InvalidArgumentException;
use Tests\TestCase;

/**
 * Wave 4, lane 5 — the video library: the app port of the operator's Coalition
 * multi-track player (mockups/v3/shared/video-player.html). The catalog is
 * config-driven (config/cga/media.php, generated by
 * scripts/i18n/build_media_registry.mjs), so these pins read config, not the DB.
 *
 * What this proves:
 *  - A GUEST reads it. The library is teaching content — public, never walled.
 *  - The five things lane 11's APP_PORT_NOTE said to get right are ENFORCED in
 *    the registry the player consumes, so a regression re-introducing any of
 *    them fails here rather than 404-ing a track in a viewer's face.
 */
class VideoLibraryPageTest extends TestCase
{
    public function test_a_guest_reads_the_video_library_on_a_public_screen(): void
    {
        $this->get('/videos')
            ->assertOk()
            ->assertInertia(fn (Assert $page) => $page
                ->component('Learn/VideoLibrary')
                ->has('surface')
                ->has('videos')
                ->where('videos.0.id', 'v-affiliate-report'));
    }

    public function test_the_base_url_is_null_until_a_media_host_is_configured(): void
    {
        // No media ships in the repo: the player must render the labelled poster
        // placeholder, which it keys on a null base URL.
        $this->assertNull(MediaMeta::baseUrl());
        $this->get('/videos')
            ->assertOk()
            ->assertInertia(fn (Assert $page) => $page->where('baseUrl', null));
    }

    /** Gotcha 4 — a language with no media (ht) yields no track, ever. */
    public function test_no_video_offers_a_track_with_no_media(): void
    {
        foreach (MediaMeta::all() as $video) {
            foreach (['audio', 'captions'] as $kind) {
                $codes = array_column($video[$kind], 'code');
                $this->assertNotContains('ht', $codes,
                    "video {$video['id']} offers an ht {$kind} track, which has no media");
            }
        }
    }

    /**
     * Gotcha 3 — the Chinese track code is the BCP-47 tag (cmn-Hans), and it
     * carries the app locale (zh-Hans) so the player can link it to a zh-Hans
     * reader. The two are distinct and both are needed.
     */
    public function test_the_chinese_track_is_bcp47_and_links_to_the_zh_hans_locale(): void
    {
        $langs = MediaMeta::languages();

        $this->assertArrayHasKey('cmn-Hans', $langs, 'the Chinese track code must be the BCP-47 tag');
        $this->assertArrayNotHasKey('zho_Hans', $langs, 'no FLORES/639-2 codes belong in a <track srclang>');
        $this->assertSame('zh-Hans', $langs['cmn-Hans']['locale']);
    }

    /**
     * Gotcha 2 — subject keeps its spaces (the filesystem token) and token
     * keeps its hyphens; the two are never derived from each other.
     */
    public function test_subject_keeps_spaces_and_token_keeps_hyphens(): void
    {
        $affiliate = MediaMeta::for('v-affiliate-report');

        $this->assertSame('Affiliate Report', $affiliate['subject']);
        $this->assertSame('Affiliate Report-Silent.mp4', $affiliate['master']);
    }

    public function test_an_unknown_media_id_throws(): void
    {
        $this->expectException(InvalidArgumentException::class);
        MediaMeta::for('v-does-not-exist');
    }
}
