<?php

namespace App\Services\Autoscale;

use App\Models\AutoscaleRun;
use App\Services\AuditService;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

/**
 * Set-based singles for ONE claimed batch (pull engine, 2026-07-19).
 *
 * The statements are the orchestrator's proven processSinglesLevel five,
 * verbatim, with the work-list filter changed from "the whole adm level"
 * (up to 700k rows in one unreclaimable bite) to "this worker's claim_token"
 * (≤15k rows, minutes per batch, reclaimed in ≤30 min if the worker dies).
 *
 * Parallel safety: batches partition items row-atomically (SKIP LOCKED at
 * claim), each legislature appears in exactly one item, and every statement
 * is NOT-EXISTS idempotent per legislature — two tokens can never
 * double-mint a founding map. A crashed batch's redo is clean.
 *
 * Founding map (active) + single at-large district (row shape =
 * InitialDistrictMapService::clampUnassignedLeafGiants) + membership +
 * spatial stats, then flip the items done. Drift is INFORMATIONAL — the
 * seating law forbids total-forcing.
 */
class SinglesBatchProcessor
{
    /** @return int items completed in this batch */
    public function process(AutoscaleRun $run, string $token): int
    {
        $itemFilter = "ai.run_id = ? AND ai.kind = 'single' AND ai.status = 'running' AND ai.claim_token = ?";
        $params     = [$run->id, $token];

        // 1. Founding maps — created directly ACTIVE: the founding context
        //    (setup, v1 maps) activates without a board, same as the founder's
        //    manual v1 maps. Legislatures that already have an active map
        //    (operator work) are left untouched.
        DB::statement("
            INSERT INTO legislature_district_maps
                (id, legislature_id, name, description, status, effective_start, created_at, updated_at)
            SELECT gen_random_uuid(), l.id, 'Founding Map',
                   'Auto-generated by full-scale autoscale (True All Scale, 2026-07-18) — single at-large district.',
                   'active', CURRENT_DATE, now(), now()
              FROM autoscale_items ai
              JOIN legislatures l ON l.id = ai.legislature_id AND l.deleted_at IS NULL
             WHERE {$itemFilter}
               AND NOT EXISTS (SELECT 1 FROM legislature_district_maps m
                                WHERE m.legislature_id = l.id
                                  AND m.status = 'active'
                                  AND m.deleted_at IS NULL)
        ", $params);

        // 2. The single at-large district: jurisdiction_id = self, district 1,
        //    seats = type_a (already ∈ [floor, ceiling] from sizing).
        DB::statement("
            INSERT INTO legislature_districts
                (id, legislature_id, jurisdiction_id, district_number, seats,
                 target_population, actual_population, status,
                 fractional_seats, floor_override, map_id, created_at, updated_at)
            SELECT gen_random_uuid(), l.id, l.jurisdiction_id, 1, l.type_a_seats,
                   COALESCE(j.population, 0), COALESCE(j.population, 0), 'active',
                   l.type_a_seats::numeric, false, m.map_id, now(), now()
              FROM autoscale_items ai
              JOIN legislatures l ON l.id = ai.legislature_id AND l.deleted_at IS NULL
              JOIN jurisdictions j ON j.id = l.jurisdiction_id
             CROSS JOIN LATERAL (
                   SELECT m2.id AS map_id FROM legislature_district_maps m2
                    WHERE m2.legislature_id = l.id AND m2.status = 'active' AND m2.deleted_at IS NULL
                    ORDER BY m2.created_at DESC LIMIT 1
             ) m
             WHERE {$itemFilter}
               AND NOT EXISTS (SELECT 1 FROM legislature_districts d
                                WHERE d.map_id = m.map_id AND d.deleted_at IS NULL)
        ", $params);

        // 3. Membership: the jurisdiction itself (ldj XOR: jurisdiction side).
        DB::statement("
            INSERT INTO legislature_district_jurisdictions (id, district_id, jurisdiction_id)
            SELECT gen_random_uuid(), d.id, d.jurisdiction_id
              FROM autoscale_items ai
              JOIN legislatures l ON l.id = ai.legislature_id AND l.deleted_at IS NULL
             CROSS JOIN LATERAL (
                   SELECT m2.id AS map_id FROM legislature_district_maps m2
                    WHERE m2.legislature_id = l.id AND m2.status = 'active' AND m2.deleted_at IS NULL
                    ORDER BY m2.created_at DESC LIMIT 1
             ) m
              JOIN legislature_districts d ON d.map_id = m.map_id AND d.deleted_at IS NULL
             WHERE {$itemFilter}
               AND d.jurisdiction_id IS NOT NULL
               AND NOT EXISTS (SELECT 1 FROM legislature_district_jurisdictions x
                                WHERE x.district_id = d.id)
        ", $params);

        // 4. Spatial stats, mirroring DistrictingService::recomputeDistrict:
        //    single-member districts are contiguous BY DEFINITION; parts +
        //    hull ratio from the (simplify-laddered, validity-repaired) geom.
        //    Scoped to the at-large district of the ACTIVE map (self-scoped,
        //    number 1) — never a blanket stamp over other districts an
        //    adopted operator map might hold.
        DB::statement("
            UPDATE legislature_districts d
               SET num_geom_parts    = ST_NumGeometries(g.geom),
                   convex_hull_ratio = ROUND((ST_Area(g.geom) / NULLIF(ST_Area(ST_ConvexHull(g.geom)), 0))::numeric, 6),
                   is_contiguous     = true,
                   updated_at        = now()
              FROM autoscale_items ai
              JOIN legislatures l ON l.id = ai.legislature_id AND l.deleted_at IS NULL
              JOIN jurisdictions j ON j.id = l.jurisdiction_id AND j.geom IS NOT NULL
             CROSS JOIN LATERAL (
                   SELECT m2.id AS map_id FROM legislature_district_maps m2
                    WHERE m2.legislature_id = l.id AND m2.status = 'active' AND m2.deleted_at IS NULL
                    ORDER BY m2.created_at DESC LIMIT 1
             ) m
             CROSS JOIN LATERAL (
                   SELECT CASE WHEN ST_NPoints(j.geom) > 1000000 THEN ST_MakeValid(ST_Simplify(j.geom, 0.01))
                               WHEN ST_NPoints(j.geom) > 50000  THEN ST_MakeValid(ST_Simplify(j.geom, 0.001))
                               ELSE ST_MakeValid(j.geom) END AS geom
             ) g
             WHERE {$itemFilter}
               AND d.legislature_id = l.id
               AND d.map_id = m.map_id
               AND d.jurisdiction_id = l.jurisdiction_id
               AND d.district_number = 1
               AND d.deleted_at IS NULL
               AND d.num_geom_parts IS NULL
        ", $params);

        // 4b. Geometry-less leaves still get the definitional contiguity flag
        //     (recomputeDistrict writes true for every single-member district
        //     regardless of geometry) — viewers must not render "not yet
        //     computed" for a lawful at-large council.
        DB::statement("
            UPDATE legislature_districts d
               SET is_contiguous = true, updated_at = now()
              FROM autoscale_items ai
              JOIN legislatures l ON l.id = ai.legislature_id AND l.deleted_at IS NULL
             CROSS JOIN LATERAL (
                   SELECT m2.id AS map_id FROM legislature_district_maps m2
                    WHERE m2.legislature_id = l.id AND m2.status = 'active' AND m2.deleted_at IS NULL
                    ORDER BY m2.created_at DESC LIMIT 1
             ) m
             WHERE {$itemFilter}
               AND d.legislature_id = l.id
               AND d.map_id = m.map_id
               AND d.jurisdiction_id = l.jurisdiction_id
               AND d.district_number = 1
               AND d.deleted_at IS NULL
               AND d.is_contiguous IS NULL
        ", $params);

        // 5. Flip the batch's items done, seats/drift recorded from the map
        //    that actually exists (drift is INFORMATIONAL — the seating law
        //    forbids total-forcing; a single district drifts only when a
        //    pre-existing operator map is being adopted).
        DB::statement("
            UPDATE autoscale_items ai
               SET status = 'done',
                   seats_seated = s.seated,
                   drift = s.seated - COALESCE(ai.seats_expected, 0),
                   started_at = COALESCE(ai.started_at, now()),
                   finished_at = now(),
                   updated_at = now()
              FROM (
                    SELECT ai2.id, COALESCE(SUM(d.seats), 0) AS seated
                      FROM autoscale_items ai2
                      JOIN legislatures l ON l.id = ai2.legislature_id AND l.deleted_at IS NULL
                      LEFT JOIN legislature_district_maps m
                             ON m.legislature_id = l.id AND m.status = 'active' AND m.deleted_at IS NULL
                      LEFT JOIN legislature_districts d
                             ON d.map_id = m.id AND d.deleted_at IS NULL
                     WHERE ai2.run_id = ? AND ai2.kind = 'single'
                       AND ai2.status = 'running' AND ai2.claim_token = ?
                     GROUP BY ai2.id
              ) s
             WHERE ai.id = s.id
               AND s.seated > 0
        ", $params);

        // Anything still claimed in this batch has no seated district even
        // after the passes above (no legislature row? no active map?) —
        // surface it for review instead of looping forever.
        DB::table('autoscale_items')
            ->where('run_id', $run->id)
            ->where('kind', 'single')
            ->where('status', 'running')
            ->where('claim_token', $token)
            ->update([
                'status'      => 'review',
                'reason'      => 'set-based single-district seeding produced no seated district',
                'finished_at' => now(),
                'updated_at'  => now(),
            ]);

        // ONE summary audit append per batch — never 700k chain entries.
        $doneCount = (int) DB::table('autoscale_items')
            ->where('run_id', $run->id)->where('kind', 'single')
            ->where('claim_token', $token)->where('status', 'done')->count();

        app(AuditService::class)->append(
            module: 'elections',
            event: 'autoscale.singles_generated',
            payload: [
                'run_id'         => (string) $run->id,
                'batch'          => $token,
                'maps_generated' => $doneCount,
                'shape'          => 'single at-large district (seats = type_a, member = self)',
                'generator'      => 'SinglesBatchProcessor set-based singles (pull engine, 2026-07-19)',
            ],
            ref: 'WF-ELE-02',
        );

        Log::info('Autoscale singles batch complete', [
            'run_id' => $run->id, 'batch' => $token, 'done' => $doneCount,
        ]);

        return $doneCount;
    }
}
