<?php

// Display labels only. Loading these static registries does not boot Laravel,
// run seeders, or read a database. Run after a form/clock registry change.
require dirname(__DIR__).'/vendor/autoload.php';

use App\Domain\Forms\FormRegistry;
use Database\Seeders\ClockRegistrySeeder;

$catalog = [
    'forms' => array_map(fn ($form) => $form['name'], FormRegistry::FORMS),
    'aliases' => FormRegistry::ALIASES,
    'clocks' => array_column(ClockRegistrySeeder::registry(), 'name', 'id'),
];
$output = '// Generated by scripts/export_ui_reference_labels.php. Labels only; never rules or defaults.'."\n"
    .'export default '.json_encode($catalog, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES).";\n";
$path = dirname(__DIR__).'/resources/js/registry/referenceLabels.generated.js';
if (in_array('--check', $argv, true)) {
    if (! is_file($path) || file_get_contents($path) !== $output) {
        fwrite(STDERR, "UI reference labels need regeneration.\n");
        exit(1);
    }
    echo "UI reference labels match the canonical registries.\n";
    exit(0);
}
file_put_contents($path, $output);
echo "UI reference labels generated.\n";
