<?php

namespace App\Support;

use InvalidArgumentException;

/**
 * MediaMeta — resolves the video library catalog for the multi-track player
 * (Learn · video library). The production analog of the mockups'
 * CGA.fixtures.v2.learn.videos, modelled on SurfaceMeta::for().
 *
 * The registry lives in config/cga/media.php, generated by
 * scripts/i18n/build_media_registry.mjs from lane 11's subjects.json +
 * languages.json (so it can never drift from the media on disk). Unknown video
 * ids throw — the same posture as SurfaceMeta.
 *
 * No media ships in the repo. `baseUrl()` is env-driven (CGA_MEDIA_BASE_URL);
 * null means the player renders the labelled poster placeholder and lights up
 * with real playback the moment the operator points it at the media host.
 */
final class MediaMeta
{
    /** The media host base URL, or null (placeholder mode). */
    public static function baseUrl(): ?string
    {
        $url = config('cga.media.base_url');

        return is_string($url) && $url !== '' ? rtrim($url, '/') : null;
    }

    /**
     * BCP-47 track code -> {name, native, dir, locale}. `name` is the media
     * filename token; `locale` is the app locale a track links to, or null.
     *
     * @return array<string, array{name: string, native: string, dir: string, locale: string|null}>
     */
    public static function languages(): array
    {
        return config('cga.media.languages', []);
    }

    /**
     * The whole catalog, each record enriched with the track language table it
     * needs (so a page can hand one video straight to the player).
     *
     * @return list<array<string, mixed>>
     */
    public static function all(): array
    {
        return array_map(self::enrich(...), config('cga.media.videos', []));
    }

    /**
     * One video by id, or throw. Shaped exactly like an all() element.
     *
     * @return array<string, mixed>
     */
    public static function for(string $id): array
    {
        foreach (config('cga.media.videos', []) as $video) {
            if (($video['id'] ?? null) === $id) {
                return self::enrich($video);
            }
        }

        throw new InvalidArgumentException(
            "Unknown media id [{$id}] — regenerate config/cga/media.php "
            . '(node scripts/i18n/build_media_registry.mjs) or check the id.'
        );
    }

    /** Every registered video id (for the registry cross-check test). */
    public static function ids(): array
    {
        return array_map(static fn (array $v): string => $v['id'], config('cga.media.videos', []));
    }

    /**
     * Attach per-track display metadata (name/native/dir/locale) so the client
     * never has to cross-reference two structures, and a duration fallback.
     *
     * @param  array<string, mixed>  $video
     * @return array<string, mixed>
     */
    private static function enrich(array $video): array
    {
        $langs = self::languages();

        $tracks = static function (array $codes) use ($langs): array {
            $out = [];
            foreach ($codes as $code) {
                if (! isset($langs[$code])) {
                    continue; // a code with no language row can never render a track
                }
                $out[] = [
                    'code'   => $code,
                    'name'   => $langs[$code]['name'],
                    'native' => $langs[$code]['native'],
                    'dir'    => $langs[$code]['dir'],
                    'locale' => $langs[$code]['locale'],
                ];
            }

            return $out;
        };

        return [
            'id'       => $video['id'],
            'subject'  => $video['subject'],
            'token'    => $video['token'] ?? null,
            'slug'     => $video['slug'] ?? null,
            'master'   => $video['master'] ?? null,
            'title'    => $video['title'] ?? $video['subject'],
            'summary'  => $video['summary'] ?? null,
            'poster'   => $video['poster'] ?? 'learn',
            'seconds'  => $video['seconds'] ?? null,
            'audio'    => $tracks($video['audio'] ?? []),
            'captions' => $tracks($video['captions'] ?? []),
        ];
    }
}
